# .github/workflows/daily-user-post-check-job.yml

name: Daily Creator Accountability Check (10-minute Test)

# This defines the hourly schedule for testing
# The cron expression '*/10 * * * *' means "every 10 minutes"
# for every hour set it as 0 * * * *
# for daily scheduling set it as 0 0 * * *
on:
  schedule:
    - cron: '*/10 * * * *'
  # Allows you to manually trigger the workflow from the Actions tab
  workflow_dispatch:

jobs:
  run_daily_check:
    runs-on: ubuntu-latest

    steps:
      - name: Send POST request to Supabase Edge Function
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{}' ${{ secrets.SUPABASE_DAILY_CHECK_URL }}
